info:
  description: "API para la gesti\xF3n escolar con roles, estudiantes, tests personalizados\
    \ y organizaciones."
  title: SGAP API
  version: 1.0.0
openapi: 3.0.4
components:
  schemas:
    Estudiante:
      properties:
        grupo:
          type: string
        jornada:
          type: string
        organizacion:
          type: string
        usuario:
          type: string
      type: object
    Organizacion:
      type: object
      properties:
        nit:
          type: string
        nombre:
          type: string
        nombreContacto:
          type: string
        razonSocial:
          type: string
        email:
          type: string
        urlWeb:
          type: string
        direccion:
          type: string
      required:
        - nit
        - nombre
        - direccion
    Usuario:
      properties:
        identificacion:
          type: string
        organizacion:
          type: string
        password:
          type: string
        rol:
          type: string
        sexo:
          type: string
        tipoIdentificacion:
          type: string
        username:
          type: string
      type: object
    Test:
      type: object
      properties:
        titulo:
          type: string
        descripcion:
          type: string
        organizacion:
          type: string
          format: uuid
        preguntas:
          type: array
          items:
            type: string
            format: uuid
      required:
      - titulo
      - organizacion
    Pregunta:
      type: object
      properties:
        texto:
          type: string
        opciones:
          type: array
          items:
            type: string
            format: uuid
      required:
      - texto
    OpcionRespuesta:
      type: object
      properties:
        texto:
          type: string
      required:
      - texto
    FormularioRespondido:
      type: object
      properties:
        estudiante:
          type: string
          format: uuid
        test:
          type: string
          format: uuid
        observaciones:
          type: string
      required:
      - estudiante
      - test
paths:
  /estudiantes:
    get:
      responses:
        '200':
          description: Lista de estudiantes
      summary: Listar estudiantes
      tags:
      - Estudiantes
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Estudiante'
        required: true
      responses:
        '201':
          description: Estudiante creado
      summary: Crear estudiante
      tags:
      - Estudiantes
  /estudiantes/{id}:
    get:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Estudiante encontrado
      summary: Obtener estudiante por ID
      tags:
      - Estudiantes
    put:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Estudiante'
        required: true
      responses:
        '200':
          description: Estudiante actualizado
      summary: Actualizar estudiante
      tags:
      - Estudiantes
  /formulariosRespondidos:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                estudiante:
                  type: string
                observaciones:
                  type: string
                test:
                  type: string
              required:
              - estudiante
              - test
              type: object
        required: true
      responses:
        '201':
          description: Formulario respondido registrado
      summary: Crear un formulario respondido
      tags:
      - Formularios Respondidos
  /formulariosRespondidos/{estudianteId}:
    get:
      parameters:
      - in: path
        name: estudianteId
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Lista de formularios respondidos
      summary: Obtener formularios respondidos por estudiante
      tags:
      - Formularios Respondidos
  /opciones:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                pregunta:
                  type: string
                texto:
                  type: string
              required:
              - pregunta
              - texto
              type: object
        required: true
      responses:
        '201':
          description: "Opci\xF3n creada exitosamente"
      summary: "Crear una nueva opci\xF3n de respuesta"
      tags:
      - Opciones
  /opciones/{id}:
    put:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                texto:
                  type: string
              type: object
        required: true
      responses:
        '200':
          description: "Opci\xF3n actualizada"
      summary: "Actualizar una opci\xF3n de respuesta"
      tags:
      - Opciones
  /organizaciones:
    get:
      responses:
        '200':
          description: Lista de organizaciones
      summary: Listar organizaciones
      tags:
      - Organizaciones
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organizacion'
        required: true
      responses:
        '201':
          description: "Organizaci\xF3n creada"
      summary: "Crear organizaci\xF3n"
      tags:
      - Organizaciones
  /organizaciones/{id}:
    get:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: "Organizaci\xF3n encontrada"
      summary: "Obtener organizaci\xF3n por ID"
      tags:
      - Organizaciones
    put:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organizacion'
        required: true
      responses:
        '200':
          description: "Organizaci\xF3n actualizada"
      summary: "Actualizar organizaci\xF3n"
      tags:
      - Organizaciones
  /preguntas:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                test:
                  type: string
                texto:
                  type: string
              required:
              - test
              - texto
              type: object
        required: true
      responses:
        '201':
          description: Pregunta creada exitosamente
      summary: Crear una nueva pregunta
      tags:
      - Preguntas
  /preguntas/{id}:
    put:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                texto:
                  type: string
              type: object
        required: true
      responses:
        '200':
          description: Pregunta actualizada
      summary: Actualizar una pregunta
      tags:
      - Preguntas
  /tests:
    get:
      responses:
        '200':
          description: Lista de tests
      summary: Obtener todos los tests
      tags:
      - Tests
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                descripcion:
                  type: string
                titulo:
                  type: string
              required:
              - titulo
              type: object
        required: true
      responses:
        '201':
          description: Test creado exitosamente
      summary: Crear un nuevo test
      tags:
      - Tests
  /tests/{id}:
    put:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                descripcion:
                  type: string
                titulo:
                  type: string
              type: object
        required: true
      responses:
        '200':
          description: Test actualizado
      summary: Actualizar un test
      tags:
      - Tests
  /usuarios/{id}:
    get:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Usuario encontrado
      summary: Obtener usuario por ID
      tags:
      - Usuarios
    put:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
        required: true
      responses:
        '200':
          description: Usuario actualizado
      summary: Actualizar usuario
      tags:
      - Usuarios
  /usuarios:
    get:
      responses:
        '200':
          description: Lista de usuarios
      summary: Obtener usuarios
      tags:
      - Usuarios
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                identificacion:
                  type: string
                organizacion:
                  type: string
                password:
                  type: string
                rol:
                  type: string
                sexo:
                  type: string
                tipoIdentificacion:
                  type: string
                username:
                  type: string
              required:
              - username
              - password
              - rol
              type: object
        required: true
      responses:
        '201':
          description: Usuario creado
      summary: Crear usuario
      tags:
      - Usuarios
tags:
- name: Usuarios
- name: Estudiantes
- name: Organizaciones
